version: '3'
services:
  api:
    build: ./api/
    env_file:
      - ./api/.env
    ports:
      - "8080:8080"
    command: >
      sh -c "npm install &&
            npm start"
    depends_on:
      - mongo
    volumes:
      - "./api:/usr/src/app/api"
      - "/usr/src/app/api/node_modules" 
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  
  client:
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install &&
            npm start"
    volumes:
      - "./client:/usr/src/app/client"
      - "/usr/src/app/client/node_modules" 
    stdin_open: true
    links:
      - api
    # depends_on: 
    #   - api