version: '3'
services:
  api:
    build: ./api/
    env_file:
      - ./api/.env
    ports:
      - "8080:8080"
    command: >
      sh -c "yarn install &&
            yarn start"
    depends_on:
      - mongo
    volumes:
      - "./api:/usr/src/app/api"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  
  client:
    build: ./client/
    command: >
      sh -c "yarn install &&
             yarn start"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app/client"
    stdin_open: true
    links:
      - api
    # depends_on: 
    #   - api