# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI

on:
  push:
    paths:
      - 'api/**.js'
  pull_request:
    paths:
      - 'api/**.js'
    

jobs:
  API_LINT_TEST:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./api/
    - run: npm install eslint --save
      working-directory: ./api/
    - run: npm run build --if-present
      working-directory: ./api/
    - run: npm test --if-present
      working-directory: ./api/
    