# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths: [ 'api/**' ]
  pull_request:
    paths: [ 'api/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx  
    - name: Install packages,lint,build and Unit testing
      working-directory: ./api
      run: |
        npm install
        CI=true npm run build
        CI=true npm test
