# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths:
    - 'api/**' 
  pull_request:
    paths:
    - 'api/**'

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v2
      name: Check out repository
    - uses: actions/setup-node@v1
      name: Set up Node.js
      with:
        node-version: 14.x
      
    - run: eslint . --ext .js,.jsx,.ts,.tsx
      name: Run ESLint
      
      
    - run: |
        npm ci
        npm run build
        npm test
      name: Install packages,lint,build and Unit testing
        
